# Generated by Django 6.0.3 on 2026-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("main", "0002_alter_category_slug_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "ВУПСЕНЬ"},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "product_size"),
                name="unique_cart_product_size",
            ),
        ),
    ]
