# Generated by Django 6.0.5 on 2026-05-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Itemssssssss"},
        ),
    ]
