# Generated by Django 6.0.5 on 2026-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_options"),
        ("main", "0002_alter_category_slug_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Cart item 🌑",
                "verbose_name_plural": "Cart items ☀️",
            },
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="cart_item_quantity_gt_0"
            ),
        ),
    ]
